version: "3"

services:
  goservice1:
    deploy:
      mode: replicated
      replicas: 3
    build:
      context: go-service-1
      target: builder
    networks:
      - mynetwork

  goservice2:
    deploy:
      mode: replicated
      replicas: 3
    build:
      context: go-service-2
      target: builder
    networks:
      - mynetwork

  goauth:
    build:
      context: go-auth
      target: builder
    networks:
      - mynetwork

  web:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - mynetwork
    volumes:
      - ./nginx-web.conf:/etc/nginx/nginx.conf:ro

  load-balancer:
    image: nginx:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
