version: "3"

services:
  goservice:
    build:
      context: go-service
      target: builder
    networks:
      - mynetwork

  goauth:
    build:
      context: go-auth
      target: builder
    networks:
      - mynetwork

  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - mynetwork
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
